# AUTO-GENERATED by auto-adk generation.
# This file drives the autonomous evolve loop.
# Edit with care — see: https://auto-adk.dev/docs/loop

"""Check the proposer's generated claims against the run record. Stdlib only.

Validates whether proposals are supported by recorded evidence, contradicted by
subsequent runs, or duplicate claims already evaluated.
"""
from __future__ import annotations


def describe_checks() -> dict:
    """Return the verdicts this checker can reach."""
    return {
        "supported": "the condition is confirmed by the cited run record",
        "unsupported": "the cited record lacks necessary evidence or metric data",
        "contradicted": "a subsequent run already refuted or superseded this proposal",
        "duplicate": "the proposal makes the same claim about a previously analyzed condition",
    }


def validate_proposals(proposals: list, runs: list) -> dict:
    """Sort proposals into supported and rejected sets based on the run record."""
    supported = []
    rejected = []
    seen = set()

    runs_by_exp = {r["experiment"]: r for r in runs}

    for p in proposals:
        det = p.get("detector")
        exp = p.get("experiment")

        if det in seen:
            rejected.append({
                **p,
                "verdict": "duplicate",
                "why": f"detector {det!r} has already been raised in this proposal batch",
            })
            continue

        if exp and exp not in runs_by_exp:
            rejected.append({
                **p,
                "verdict": "unsupported",
                "why": f"cited experiment {exp!r} was not found in the run record",
            })
            continue

        cited_run = runs_by_exp.get(exp) if exp else None

        if det == "evidence_unsupported":
            ev = p.get("evidence", {})
            score_val = ev.get("evidence_score")
            if score_val is not None and score_val >= 0.50:
                rejected.append({
                    **p,
                    "verdict": "contradicted",
                    "why": f"evidence review score {score_val} is >= 0.50",
                })
                continue

        if det == "efficiency_reduction":
            if cited_run and (cited_run.get("observed_value") or 0.0) < 95.0:
                rejected.append({
                    **p,
                    "verdict": "unsupported",
                    "why": "cited run did not reach the >=95.0% threshold required for efficiency reduction",
                })
                continue

        seen.add(det)
        supported.append(p)

    return {
        "supported": supported,
        "rejected": rejected,
        "n_supported": len(supported),
        "n_rejected": len(rejected),
        "checks": describe_checks(),
    }
