# AUTO-GENERATED by auto-adk generation.
# This file drives the autonomous evolve loop.
# Edit with care — see: https://auto-adk.dev/docs/loop

"""Proposer for the tutoring-flow research loop. Stdlib only.

Reads the run record, audits, and evaluation details to detect structural
conditions (e.g., unsupported peer-review evidence, high mastery enabling
efficiency pruning, sensitivity to cohort heterogeneity, or ordering ablation)
and proposes ranked, machine-checkable hypotheses for follow-up experiments.
"""
from __future__ import annotations

import json
import os
import re
from typing import Any

DETECTORS: dict[str, dict] = {
    "evidence_unsupported": {
        "condition": "peer-review evidence score is below 0.50 or status is unsupported",
        "asks": "whether the claims are circular, hardcoded, or lack valid empirical ground",
        "priority": 100,
    },
    "differentiated_mastery": {
        "condition": "mastery is very high (>=95%) but still below the 99% target",
        "asks": "whether adding formative feedback / worked-example teaching lifts the low-aptitude floor to reach >=99% mean mastery",
        "priority": 95,
    },
    "efficiency_reduction": {
        "condition": "mean mastery >= 95% achieved with 10 passes; asks if streamlined scheduling maintains target",
        "asks": "whether an optimized 8-pass adaptive flow maintains >=95% mastery with lower instructional overhead",
        "priority": 85,
    },
    "cohort_heterogeneity_robustness": {
        "condition": "strategy succeeds on baseline cohort; tests robustness under increased cohort variance and size",
        "asks": "whether the adaptive distributed tutoring strategy maintains >=92% mastery across a wider cohort",
        "priority": 75,
    },
    "ordering_strategy_ablation": {
        "condition": "high mastery reached under interleaved ordering; tests if difficulty-first ordering matches or improves performance",
        "asks": "whether difficulty-first ordering under adaptive review matches interleaved ordering (>=95% mastery)",
        "priority": 65,
    },
}


def describe_detectors() -> dict:
    """Return the conditions this proposer can recognise."""
    return {
        name: {"condition": spec["condition"], "asks": spec["asks"]}
        for name, spec in DETECTORS.items()
    }


def _load_json(path: str) -> Any:
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def _extract_evidence_score(rationale: str) -> float | None:
    """Parse evidence review score from the rationale string if present."""
    if not rationale:
        return None
    match = re.search(r"\[evidence_review\]\s+Evidence:\s+score=([0-9]*\.?[0-9]+)", rationale)
    if match:
        try:
            return float(match.group(1))
        except ValueError:
            return None
    if "unsupported" in rationale.lower():
        return 0.0
    return None


_DETAIL_MARKERS: tuple = (
    "mastered_topic_pct",
    "per_topic_mastery",
    "n_steps",
    "order",
    "passes",
    "review_spacing",
    "review_mode",
)


def _extract_detail(trace: Any) -> dict | None:
    """Extract evaluate node detail payload from trace."""
    stack = [trace]
    while stack:
        item = stack.pop()
        if isinstance(item, dict):
            if "detail" in item and isinstance(item["detail"], dict):
                candidate = item["detail"]
                if any(k in candidate for k in _DETAIL_MARKERS):
                    return candidate
            stack.extend(item.values())
        elif isinstance(item, list):
            stack.extend(item)
    return None


def collect_run_record(root: str) -> dict:
    """Gather run score, trace detail, and audit state across all experiments."""
    research = os.path.join(root, "research")
    if not os.path.isdir(research):
        return {"runs": [], "n_runs": 0, "n_experiments": 0}

    runs = []
    experiments = sorted(os.listdir(research))
    for experiment in experiments:
        runs_dir = os.path.join(research, experiment, "runs")
        if not os.path.isdir(runs_dir):
            continue
        for run_id in sorted(os.listdir(runs_dir)):
            base = os.path.join(runs_dir, run_id)
            score_path = os.path.join(base, "score.json")
            if not os.path.exists(score_path):
                continue
            score = _load_json(score_path)

            detail = None
            trace_path = os.path.join(base, "trace.json")
            if os.path.exists(trace_path):
                try:
                    trace = _load_json(trace_path)
                    detail = _extract_detail(trace)
                except Exception:
                    detail = None

            runs.append({
                "experiment": experiment,
                "run_id": run_id,
                "score": score,
                "gates_passed": score.get("gates_passed", False),
                "observed_value": score.get("observed_value"),
                "detail": detail,
            })

    return {
        "runs": runs,
        "n_runs": len(runs),
        "n_experiments": len(experiments),
    }


def extraction_coverage(root: str) -> dict:
    """Report readability of evaluation detail across runs."""
    record = collect_run_record(root)
    unreadable = [
        f"{run['experiment']}/{run['run_id']}"
        for run in record["runs"]
        if run["detail"] is None
    ]
    return {
        "n_runs": record["n_runs"],
        "n_readable": record["n_runs"] - len(unreadable),
        "unreadable": unreadable,
    }


def propose_next_hypotheses(root: str) -> dict:
    """Detect conditions in run records and emit prioritized follow-up proposals."""
    record = collect_run_record(root)
    if not record["runs"]:
        return {
            "proposals": [],
            "resolved": [],
            "n_resolved": 0,
            "detectors": list(DETECTORS),
        }

    proposals: list[dict] = []
    resolved: list[dict] = []

    # Check for evidence review issues first across all runs
    for run in record["runs"]:
        score = run["score"]
        rationale = score.get("rationale", "")
        ev_score = _extract_evidence_score(rationale)
        if ev_score is not None and ev_score < 0.50:
            proposals.append({
                "detector": "evidence_unsupported",
                "priority": DETECTORS["evidence_unsupported"]["priority"],
                "experiment": run["experiment"],
                "run_id": run["run_id"],
                "evidence": {
                    "evidence_score": ev_score,
                    "rationale": rationale[:200],
                },
                "question": (
                    f"Why did the evidence reviewer assign score {ev_score:.2f} "
                    f"to {run['experiment']}, and can the methodology be verified?"
                ),
            })

    # Find highest valid observed value and its run
    valid_runs = [r for r in record["runs"] if r.get("observed_value") is not None and r.get("gates_passed")]
    if not valid_runs:
        return {
            "proposals": proposals,
            "resolved": resolved,
            "n_resolved": len(resolved),
            "detectors": list(DETECTORS),
        }

    best_run = max(valid_runs, key=lambda r: r["observed_value"])
    best_mastery = float(best_run["observed_value"])
    exp_slug = best_run["experiment"]
    run_id = best_run["run_id"]
    detail = best_run.get("detail") or {}

    passes = detail.get("passes", 10)
    order = detail.get("order", "interleaved")
    review_mode = detail.get("review_mode", "adaptive")

    tested_experiments = {r["experiment"] for r in record["runs"]}

    feedback_on = bool(detail.get("feedback", False))

    # 0. Differentiated-mastery proposal (highest priority follow-up).
    # If mastery is very high but still short of 99%, add formative feedback /
    # worked-example teaching to lift the low-aptitude floor toward total mastery.
    feedback_tested = any(
        "feedback" in exp or "differentiat" in exp for exp in tested_experiments
    )
    if 95.0 <= best_mastery < 99.0 and not feedback_on:
        if feedback_tested:
            resolved.append({
                "detector": "differentiated_mastery",
                "resolved_by": exp_slug,
            })
        else:
            proposals.append({
                "detector": "differentiated_mastery",
                "priority": DETECTORS["differentiated_mastery"]["priority"],
                "experiment": exp_slug,
                "run_id": run_id,
                "evidence": {
                    "best_mastery": best_mastery,
                    "feedback": feedback_on,
                    "passes": passes,
                },
                "question": (
                    "Does adding formative feedback / worked-example teaching to "
                    "the adaptive distributed flow (12 passes) reach >=99.0% mean "
                    f"mastery (from {best_mastery:.2f}%)?"
                ),
            })

    # 1. Efficiency Reduction Proposal
    # If >= 95% mastery is achieved, can we reach >=95% with 8 passes instead of 10?
    efficiency_tested = any("efficiency" in exp or "reduced-passes" in exp for exp in tested_experiments)
    if best_mastery >= 95.0 and passes >= 10:
        if efficiency_tested:
            resolved.append({
                "detector": "efficiency_reduction",
                "resolved_by": exp_slug,
            })
        else:
            proposals.append({
                "detector": "efficiency_reduction",
                "priority": DETECTORS["efficiency_reduction"]["priority"],
                "experiment": exp_slug,
                "run_id": run_id,
                "evidence": {
                    "best_mastery": best_mastery,
                    "passes": passes,
                    "steps": detail.get("n_steps"),
                },
                "question": (
                    f"Does an 8-pass adaptive distributed tutoring flow reach >=95.0% "
                    f"mean mastery (from current {best_mastery:.2f}% at 10 passes) while reducing total instruction steps?"
                ),
            })

    # 2. Cohort Heterogeneity Robustness Proposal
    heterogeneity_tested = any("heterogen" in exp or "robust" in exp or "cohort-80" in exp for exp in tested_experiments)
    if best_mastery >= 95.0:
        if heterogeneity_tested:
            resolved.append({
                "detector": "cohort_heterogeneity_robustness",
                "resolved_by": exp_slug,
            })
        else:
            proposals.append({
                "detector": "cohort_heterogeneity_robustness",
                "priority": DETECTORS["cohort_heterogeneity_robustness"]["priority"],
                "experiment": exp_slug,
                "run_id": run_id,
                "evidence": {
                    "best_mastery": best_mastery,
                    "baseline_cohort_size": 40,
                },
                "question": (
                    f"Does the adaptive distributed tutoring strategy maintain >=92.0% mean "
                    f"mastery on an expanded, heterogeneous cohort of 80 learners?"
                ),
            })

    # 3. Ordering Strategy Ablation Proposal
    ordering_ablation_tested = any("difficulty-order" in exp or "ablation" in exp for exp in tested_experiments)
    if best_mastery >= 95.0 and order == "interleaved":
        if ordering_ablation_tested:
            resolved.append({
                "detector": "ordering_strategy_ablation",
                "resolved_by": exp_slug,
            })
        else:
            proposals.append({
                "detector": "ordering_strategy_ablation",
                "priority": DETECTORS["ordering_strategy_ablation"]["priority"],
                "experiment": exp_slug,
                "run_id": run_id,
                "evidence": {
                    "best_mastery": best_mastery,
                    "current_order": order,
                    "review_mode": review_mode,
                },
                "question": (
                    "Does a difficulty-ordered flow with adaptive distributed review "
                    "reach >=95.0% mean mastery, matching interleaved ordering?"
                ),
            })

    # Sort proposals by priority descending
    proposals.sort(key=lambda p: p.get("priority", 0), reverse=True)

    return {
        "proposals": proposals,
        "resolved": resolved,
        "n_resolved": len(resolved),
        "detectors": list(DETECTORS),
    }
