# AUTO-GENERATED by auto-adk generation.
# This file drives the autonomous evolve loop.
# Edit with care — see: https://auto-adk.dev/docs/loop

"""Experiment templates for the tutoring-flow research loop.

Maps proposal detector types to experiment definitions with configuration overrides
and machine-checkable predictions. Stdlib only.
"""
from __future__ import annotations

TEMPLATES: dict[str, dict] = {
    "differentiated_mastery": {
        "name": "formative-feedback-differentiated",
        "source": "006-does-adaptive-tightly-spaced",
        "summary": "Add formative feedback / worked-example teaching (raises the effectiveness floor for weaker learners) to the adaptive distributed flow over 12 passes to reach near-total mastery.",
        "predict": lambda ev: {
            "claim": "Adaptive distributed flow with formative feedback over 12 passes reaches >=99.0% mean mastery",
            "metric": "mean_mastery_pct",
            "op": ">=",
            "value": 99.0,
            "refuted_if": "mean_mastery_pct < 99.0",
        },
        "params_override": {
            "config": {
                "order": "interleaved",
                "passes": 12,
                "review_spacing": 2,
                "review_mode": "adaptive",
                "scaffolding": True,
                "feedback": True,
                "mastery_threshold": 0.8,
                "cohort_size": 40,
                "seed": 2026,
            }
        },
    },
    "evidence_unsupported": {
        "name": "verify-evidence-fidelity",
        "source": "006-does-adaptive-tightly-spaced",
        "summary": "Re-run evaluation with rigorous assertions to eliminate circular or unsupported evidence.",
        "predict": lambda ev: {
            "claim": "Re-verified tutoring flow maintains mean mastery >= 95.0% under strict audit",
            "metric": "mean_mastery_pct",
            "op": ">=",
            "value": 95.0,
            "refuted_if": "mean_mastery_pct < 95.0",
        },
        "params_override": {
            "config": {
                "order": "interleaved",
                "passes": 10,
                "review_spacing": 2,
                "review_mode": "adaptive",
                "scaffolding": True,
                "mastery_threshold": 0.8,
                "cohort_size": 40,
                "seed": 2026,
            }
        },
    },
    "efficiency_reduction": {
        "name": "streamlined-adaptive-passes",
        "source": "006-does-adaptive-tightly-spaced",
        "summary": "Reduce spiral passes from 10 to 8 to test if the adaptive distributed practice maintains >=95.0% mastery with fewer steps.",
        "predict": lambda ev: {
            "claim": "Streamlined 8-pass adaptive flow reaches >=95.0% mean mastery",
            "metric": "mean_mastery_pct",
            "op": ">=",
            "value": 95.0,
            "refuted_if": "mean_mastery_pct < 95.0",
        },
        "params_override": {
            "config": {
                "order": "interleaved",
                "passes": 8,
                "review_spacing": 2,
                "review_mode": "adaptive",
                "scaffolding": True,
                "mastery_threshold": 0.8,
                "cohort_size": 40,
                "seed": 2026,
            }
        },
    },
    "cohort_heterogeneity_robustness": {
        "name": "heterogeneous-cohort-robustness",
        "source": "006-does-adaptive-tightly-spaced",
        "summary": "Test adaptive distributed practice on a larger, more heterogeneous cohort (cohort_size=80) to verify robustness.",
        "predict": lambda ev: {
            "claim": "Adaptive distributed practice maintains >=92.0% mean mastery on an expanded cohort of 80 learners",
            "metric": "mean_mastery_pct",
            "op": ">=",
            "value": 92.0,
            "refuted_if": "mean_mastery_pct < 92.0",
        },
        "params_override": {
            "config": {
                "order": "interleaved",
                "passes": 10,
                "review_spacing": 2,
                "review_mode": "adaptive",
                "scaffolding": True,
                "mastery_threshold": 0.8,
                "cohort_size": 80,
                "seed": 2026,
            }
        },
    },
    "ordering_strategy_ablation": {
        "name": "difficulty-order-adaptive-ablation",
        "source": "006-does-adaptive-tightly-spaced",
        "summary": "Test difficulty-first ordering against interleaved ordering under adaptive review to assess ordering sensitivity.",
        "predict": lambda ev: {
            "claim": "Difficulty-first ordering with adaptive distributed review reaches >=95.0% mean mastery",
            "metric": "mean_mastery_pct",
            "op": ">=",
            "value": 95.0,
            "refuted_if": "mean_mastery_pct < 95.0",
        },
        "params_override": {
            "config": {
                "order": "difficulty",
                "passes": 10,
                "review_spacing": 2,
                "review_mode": "adaptive",
                "scaffolding": True,
                "mastery_threshold": 0.8,
                "cohort_size": 40,
                "seed": 2026,
            }
        },
    },
}
